disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "All The Devils Shakespeare"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "All The Devils Shakespeare"
  email = "youremail@example.com"
  image = "atd_logo.png"
  imageQuality = 96
  headline = "A Florida Non-Profit"
  bio = "A Florida Non-Profit"
